genre:
  cache:
     refresh:
       millis: 14400000
my:
  job:
    scheduler:
      pool:
        size: 1
    executor:
      queue:
        capacity: 10
      pool:
        size: 5
nbu:
  rest:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
    cron: 0 5 16,18 * * MON-FRI
jdbc:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/movieland
  username: app_owner
  password: app_owner
security:
  time-to-live:
    hours: 2
  cron: 0 30 * * * *
executor:
  timeout-millis: 5000
cors:
  origin: http://localhost:3000
