genre:
  cache:
     refresh:
       millis: 14400000
my:
  job:
    scheduler:
      pool:
        size: 1
    executor:
      queue:
        capacity: 0
      pool:
        size: 1
nbu:
  rest:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
    cron: 0 5 16,18 * * MON-FRI